---
title     : "Reproducible research workflows for psychologists"
subtitle  : "<small>Lecture title</small>"

author    : "<br />`r paste(params$author, collapse = ' & ')`"
date      : "<small>`r paste0(params$location, ', ', params$date)`</small>"
---
exclude: true

```{r child = "_setup.Rmd"}

```

---

# Agenda

1. First things first
--

2. and so on


<script src="https://cdn.jsdelivr.net/npm/medium-zoom@1.0.6/dist/medium-zoom.js"></script>
<script type="module">
import mediumZoom from 'https://cdn.jsdelivr.net/npm/medium-zoom@1.0.6/dist/medium-zoom.esm.js'

const zoomDefault = mediumZoom('#zoom-default')
const zoomMargin = mediumZoom('#zoom-margin', { margin: 45 })
</script>

<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  "HTML-CSS": {
    scale: 150,
  }
});
</script>

---
# A zoomable plot

```{r zoomable-plot, out.height = "95%", out.extra='id="zoom-margin"'}
plot(cars)
```


---
# Two columns

<!-- See CSS file -->

.pull-left-45[

- A
- B
- C

]

.pull-right-45[

```{r out.width = "100%"}
plot(cars)
```


]
